require.config({
    paths:{
        'jquery':'./libs/jquery-2.1.1',
        'swiper':'./libs/swiper-4.1.6.min',
        'scroll':'./libs/bscroll.min',
        "handlebars":'./libs/handlebars',
        'index':'./app/index',
        'render':'./app/render'
    }
})
require(['index'])